# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np

In [3]:
a1 = np.arange(10)
print("1D Array: \n" , a1)
a2 = np.arange(10).reshape(2,5)
print("2D Array: \n" , a2)

1D Array: 
 [0 1 2 3 4 5 6 7 8 9]
2D Array: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [9]:
print("Array 1: \n" , a2)
a3 = np.ones((2,5))
print("Array 2: \n" , a3)
a_vs = np.vstack((a2,a3))
print("Stacking Vertically: \n" , a_vs)

Array 1: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Array 2: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Stacking Vertically: 
 [[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [10]:
print("Array 1: \n" , a2)
a3 = np.ones((2,5))
print("Array 2: \n" , a3)
a_hs = np.hstack((a2,a3))
print("Stacking Vertically: \n" , a_hs)

Array 1: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Array 2: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Stacking Vertically: 
 [[0. 1. 2. 3. 4. 1. 1. 1. 1. 1.]
 [5. 6. 7. 8. 9. 1. 1. 1. 1. 1.]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [11]:
print("2D Array \n" , a2)
a_flat = a2.flatten()
print("1D Array \n" , a_flat)

2D Array 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
1D Array 
 [0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [12]:
a4 = np.arange(15).reshape(3,5)
print("2D Array \n" , a4)
a_flat2 = a4.flatten()
print("1D Array \n" , a_flat2)

2D Array 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
1D Array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [20]:
a5 = np.arange(15)
print("1D Array \n" , a5)
a6 = a5.reshape(5,3)
print("2D Array \n" , a6)

1D Array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
2D Array 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [24]:
a7 = np.arange(1,26).reshape(5,5)
print("Array \n" , a7)
a7_sqr = a7 ** 2
print("Square of Array \n" , a7_sqr)

Array 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Square of Array 
 [[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]
 [256 289 324 361 400]
 [441 484 529 576 625]]


## Question:8

### Create 5x6 an array and find the mean?

In [27]:
a8 = np.arange(1,31).reshape(5,6)
print("Array \n" , a8)
a8_mean = a8.mean()
print("Mean of Array \n" , a8_mean)

Array 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
Mean of Array 
 15.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [30]:
print("Array \n" , a8)
a8_stdv = np.std(a8)
print("Standard Deviation of Array \n" , a8_stdv)

Array 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
Standard Deviation of Array 
 8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [32]:
print("Array \n" , a8)
a8_median = np.median(a8)
print("Median of Array \n" , a8_median)

Array 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
Median of Array 
 15.5


## Question:11

### Find the transpose of the previous array in Q8?

In [35]:
print("Array \n" , a8)
a8_transpose = np.transpose(a8)
print("Transpose of Array \n" , a8_transpose)

Array 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
Transpose of Array 
 [[ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]
 [ 6 12 18 24 30]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [37]:
a9 = np.arange(1,17).reshape(4,4)
print("Array \n" , a9)
a9_diagsum = np.trace(a9)
print("Sum of Diagonal Elements of Array \n" , a9_diagsum)

Array 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Sum of Diagonal Elements of Array 
 34


## Question:13

### Find the determinant of the previous array in Q12?

In [41]:
print("Array \n" , a9)
a9_det = np.linalg.det(a9)
print("Determinant of Array \n" , a9_det)

Array 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Determinant of Array 
 -1.820448242817726e-31


## Question:14

### Find the 5th and 95th percentile of an array?

In [47]:
print("Array: \n", a9)
a9_p5 = np.percentile(a9, 5)
a9_p95 = np.percentile(a9, 95)
print("5th percentile of array:" ,a9_p5 )
print("95th percentile of array:" ,a9_p95 )

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
5th percentile of array: 1.75
95th percentile of array: 15.25


## Question:15

### How to find if a given array has any null values?

In [48]:
np.isnan(a9).any()

False