# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
a1 = np.zeros(10)
a1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [5]:
a2 = np.arange(10,50)
a2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [6]:
a2.shape

(40,)

5. Print the type of the previous array in question 3

In [10]:
type(a2)

numpy.ndarray

6. Print the numpy version and the configuration


In [138]:
print(np.__version__)
print(np.show_config())

1.16.5
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Laraib/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Laraib/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Laraib/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\l

7. Print the dimension of the array in question 3


In [16]:
a2.ndim

1

8. Create a boolean array with all the True values

In [18]:
a3 = np.array( [ True, True, True] )
a3

array([ True,  True,  True])

9. Create a two dimensional array




In [20]:
a4 = np.arange(8).reshape(2,4)
a4

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

10. Create a three dimensional array



In [21]:
a5 = np.arange(8).reshape(2,2,2)
a5

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [22]:
a6 = [3,6,82,9,2,73,1,4,6]
a6[::-1]

[6, 4, 1, 73, 2, 9, 82, 6, 3]

12. Create a null vector of size 10 but the fifth value which is 1 

In [23]:
a7 = np.zeros(10)
a7[4] = 1
a7

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [25]:
a8 = np.identity(3)
a8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [29]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
arr = arr.astype('float64') 
print(arr.dtype)

int32
float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [32]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

ans_multiply = arr1 * arr2
ans_multiply

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [40]:
ans_comparison = np.maximum(arr1 , arr2)
ans_comparison

array([[ 1.,  4.,  3.],
       [ 7.,  5., 12.]])

17. Extract all odd numbers from arr with values(0-9)

In [41]:
a9 = np.arange(10)
a9[1::2]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [42]:
a9[1::2] = -1
a9

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [44]:
a10 = np.arange(10)
a10[[5,6,7,8]] = 12
a10

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [46]:
a11 = np.ones((5,5))
a11[1:-1,1:-1]=0
a11

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [49]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [81]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d [0,:] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [61]:
a12 = np.arange(10).reshape(2,5)
print("a12 : \n", a12)
print()
print("a12 sliced : \n", a12[0,:])

a12 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]

a12 sliced : 
 [0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [60]:
print("a12 : \n", a12)
print()
print("a12 sliced : \n", a12[1,1])

a12 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]

a12 sliced : 
 6


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [65]:
print("a12 : \n", a12)
print()
print("a12 sliced : \n", a12[:,2:3])

a12 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]

a12 sliced : 
 [[2]
 [7]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [69]:
a13 = np.random.rand(10,10)
print("Minimum Value: " , np.min(a13))
print("Maximum Value: " , np.max(a13))

Minimum Value:  0.017354280079946327
Maximum Value:  0.9854288937754306


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [70]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
common = np.intersect1d(a, b) 
print("Common Elements: ", common)

Common Elements:  [2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [79]:
match_position = np.where(a == b)
print("Positions : ", match_position[0] )

Positions :  [1 3 5 7]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [143]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data)
print("Values..")
values = data[names != 'Will']
print(values)
#values2 = data[np.where(names != 'Will')]
#print("Values - 2..")
#print(values2)

[[-1.03667557  2.43997542 -0.10937365  0.88244981]
 [ 0.91430333  0.37880038  1.95740779  0.95288454]
 [ 2.51376292 -0.38459338 -0.6205801   0.29665965]
 [ 1.91612812 -0.97646364  0.71787054  0.14918292]
 [ 0.16885723 -0.67980514  0.3997168  -1.09318121]
 [ 0.8399947  -2.35319338 -2.26900927 -0.54494725]
 [ 0.63138102 -1.9705915   0.36631472 -1.04890317]]
Values..
[[-1.03667557  2.43997542 -0.10937365  0.88244981]
 [ 0.91430333  0.37880038  1.95740779  0.95288454]
 [ 1.91612812 -0.97646364  0.71787054  0.14918292]
 [ 0.8399947  -2.35319338 -2.26900927 -0.54494725]
 [ 0.63138102 -1.9705915   0.36631472 -1.04890317]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [148]:
print("Data Array: \n",data)
values2 = (names != 'Will') & (names!= 'Joe')
print("Values2: \n" , values2)
print(data[values2])

Data Array: 
 [[-1.03667557  2.43997542 -0.10937365  0.88244981]
 [ 0.91430333  0.37880038  1.95740779  0.95288454]
 [ 2.51376292 -0.38459338 -0.6205801   0.29665965]
 [ 1.91612812 -0.97646364  0.71787054  0.14918292]
 [ 0.16885723 -0.67980514  0.3997168  -1.09318121]
 [ 0.8399947  -2.35319338 -2.26900927 -0.54494725]
 [ 0.63138102 -1.9705915   0.36631472 -1.04890317]]
Values2: 
 [ True False False  True False False False]
[[-1.03667557  2.43997542 -0.10937365  0.88244981]
 [ 1.91612812 -0.97646364  0.71787054  0.14918292]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [150]:
a14 = np.arange(1.0,16.0).reshape(5,3)
print("Array: \n", a14)
print("Array Data Type: \n",a14.dtype)

Array: 
 [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]
Array Data Type: 
 float64


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [157]:
a15 = np.random.uniform(1,16, size=(2,2,4))
a15

array([[[11.20167223,  4.83006652,  7.01662763,  6.65374766],
        [ 4.95007776,  8.68960783,  6.96878704,  4.39617969]],

       [[15.91505463, 14.40544134, 13.10164203,  8.79472231],
        [13.31083705,  4.24858074,  6.00216643, 13.61033098]]])

33. Swap axes of the array you created in Question 32

In [162]:
print("Original: \n" , a15)
print("Swapped: \n" , np.swapaxes(a15, 0, 2))
#print("Swapped: \n" , np.swapaxes(a15, 2, 0))

Original: 
 [[[11.20167223  4.83006652  7.01662763  6.65374766]
  [ 4.95007776  8.68960783  6.96878704  4.39617969]]

 [[15.91505463 14.40544134 13.10164203  8.79472231]
  [13.31083705  4.24858074  6.00216643 13.61033098]]]
Swapped: 
 [[[11.20167223 15.91505463]
  [ 4.95007776 13.31083705]]

 [[ 4.83006652 14.40544134]
  [ 8.68960783  4.24858074]]

 [[ 7.01662763 13.10164203]
  [ 6.96878704  6.00216643]]

 [[ 6.65374766  8.79472231]
  [ 4.39617969 13.61033098]]]
Swapped: 
 [[[11.20167223 15.91505463]
  [ 4.95007776 13.31083705]]

 [[ 4.83006652 14.40544134]
  [ 8.68960783  4.24858074]]

 [[ 7.01662763 13.10164203]
  [ 6.96878704  6.00216643]]

 [[ 6.65374766  8.79472231]
  [ 4.39617969 13.61033098]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [93]:
a16 = np.arange(10)
a17 = np.sqrt(a16)
a17 = np.where( a17 < 0.5, 0, a17)
a17

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [102]:
rand1 = np.random.rand(12)
rand2 = np.random.rand(12)
max_value = np.maximum(rand1, rand2)
max_value

array([0.10435522, 0.53206835, 0.53464383, 0.17386004, 0.85419471,
       0.18390812, 0.90707724, 0.34730969, 0.41938004, 0.79082573,
       0.69627428, 0.15971828])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [101]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names_unique = np.unique(names)
names_sort = np.sort(names_unique)
print(names_sort)

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [168]:
a11 = np.array([1,2,3,4,5]) 
b11 = np.array([5,6,7,8,9])
c11 = np.setdiff1d(a11,b11)
print(c11)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [127]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print("SampleArray : \n" , sampleArray)
sampleArray2 = np.delete(sampleArray, 1, axis=1)
print("Column 2 Deleted: \n" , sampleArray2)
newColumn = np.array([[10,10,10]])
print("New Column: \n" , newColumn)
print("New Array: \n" , np.insert(sampleArray2, 1 , newColumn , axis=1))

SampleArray : 
 [[34 43 73]
 [82 22 12]
 [53 94 66]]
Column 2 Deleted: 
 [[34 73]
 [82 12]
 [53 66]]
New Column: 
 [[10 10 10]]
New Array: 
 [[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [133]:
x1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
print(x1)
y1 = np.array([[6., 23.], [-1, 7], [8, 9]])
print(y1)
dot_prod = x1.dot(y1)
dot_prod

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]


array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [137]:
a18 = np.random.randn(20)
print(a18)
a18_cumsum = np.cumsum(a18)
print(a18_cumsum)

[ 0.17288082 -0.20065637 -1.02956634 -0.83607854 -0.48943805 -0.66470652
 -0.49097882  0.13229819 -1.2587573   1.18957149 -0.26746409  0.26830253
  1.26396771  0.7716845  -1.0202423   0.11736849  0.348807   -1.41913962
 -0.15813261 -1.71816097]
[ 0.17288082 -0.02777556 -1.05734189 -1.89342043 -2.38285849 -3.04756501
 -3.53854383 -3.40624564 -4.66500293 -3.47543144 -3.74289554 -3.474593
 -2.21062529 -1.43894079 -2.45918309 -2.34181459 -1.99300759 -3.41214721
 -3.57027982 -5.28844079]
